--- 
- 
  hosts: WebServer
  become: true
  tasks:
          - name: "1. Stop service"
            tags: stop_apache
            service:
                name: apache2
                state: stopped
          - name: "2. Uninstall HTTPD/Apache"
            tags: uninstall_apache
            yum:
                name: apache2
                autoremove: yes
                purge: yes
                state: absent
